"""initial schema

Revision ID: 84bc03666d67
Revises:
Create Date: 2026-09-23 05:03:27.763193+00:00
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "84bc03666d67"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "surveys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("questions", sa.JSON(), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=True),
        sa.Column("estimated_time_minutes", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_surveys")),
    )
    with op.batch_alter_table("surveys", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_surveys_id"), ["id"], unique=False)

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("mfa_enabled", sa.Boolean(), nullable=False),
        sa.Column("mfa_secret", sa.String(length=32), nullable=True),
        sa.Column("backup_codes", sa.JSON(), nullable=True),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("location", sa.String(length=100), nullable=True),
        sa.Column("timezone", sa.String(length=50), nullable=False),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column("github_id", sa.String(length=50), nullable=True),
        sa.Column("google_id", sa.String(length=50), nullable=True),
        sa.Column("linkedin_id", sa.String(length=50), nullable=True),
        sa.Column("email_notifications", sa.Boolean(), nullable=False),
        sa.Column("push_notifications", sa.Boolean(), nullable=False),
        sa.Column("marketing_emails", sa.Boolean(), nullable=False),
        sa.Column("learning_style", sa.String(length=50), nullable=True),
        sa.Column("skill_level", sa.String(length=20), nullable=False),
        sa.Column("interests", sa.JSON(), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("login_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_users_id"), ["id"], unique=False)

    op.create_table(
        "api_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("key_hash", sa.String(length=255), nullable=False),
        sa.Column("key_prefix", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("scopes", sa.JSON(), nullable=False),
        sa.Column("rate_limit_per_hour", sa.Integer(), nullable=False),
        sa.Column("rate_limit_per_day", sa.Integer(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column("daily_usage_count", sa.Integer(), nullable=False),
        sa.Column("hourly_usage_count", sa.Integer(), nullable=False),
        sa.Column(
            "last_usage_reset",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=True,
        ),
        sa.Column("allowed_ips", sa.JSON(), nullable=True),
        sa.Column("allowed_domains", sa.JSON(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_api_keys_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_keys")),
    )
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_api_keys_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_api_keys_key_hash"), ["key_hash"], unique=True)
        batch_op.create_index(batch_op.f("ix_api_keys_user_id"), ["user_id"], unique=False)

    op.create_table(
        "courses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("short_description", sa.String(length=500), nullable=True),
        sa.Column("instructor_id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("subcategory", sa.String(length=100), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column(
            "difficulty",
            sa.Enum("beginner", "intermediate", "advanced", "expert", name="difficulty_level"),
            nullable=False,
        ),
        sa.Column("estimated_duration_hours", sa.Integer(), nullable=True),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column("thumbnail_url", sa.String(length=500), nullable=True),
        sa.Column("preview_video_url", sa.String(length=500), nullable=True),
        sa.Column("course_outline", sa.JSON(), nullable=True),
        sa.Column("learning_objectives", sa.JSON(), nullable=True),
        sa.Column("prerequisites", sa.JSON(), nullable=True),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("original_price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("is_free", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("draft", "published", "archived", "under_review", name="course_status"),
            nullable=False,
        ),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("is_featured", sa.Boolean(), nullable=False),
        sa.Column("total_enrollments", sa.Integer(), nullable=False),
        sa.Column("active_enrollments", sa.Integer(), nullable=False),
        sa.Column("completion_rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("average_rating", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("total_reviews", sa.Integer(), nullable=False),
        sa.Column("meta_title", sa.String(length=255), nullable=True),
        sa.Column("meta_description", sa.Text(), nullable=True),
        sa.Column("meta_keywords", sa.String(length=500), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["instructor_id"], ["users.id"], name=op.f("fk_courses_instructor_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_courses")),
    )
    with op.batch_alter_table("courses", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_courses_category"), ["category"], unique=False)
        batch_op.create_index(batch_op.f("ix_courses_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_courses_instructor_id"), ["instructor_id"], unique=False
        )
        batch_op.create_index(
            "ix_courses_published_category", ["is_published", "category"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_courses_slug"), ["slug"], unique=True)
        batch_op.create_index(batch_op.f("ix_courses_title"), ["title"], unique=False)

    op.create_table(
        "device_registrations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("device_name", sa.String(length=100), nullable=False),
        sa.Column("device_type", sa.String(length=50), nullable=False),
        sa.Column("device_fingerprint", sa.String(length=255), nullable=False),
        sa.Column("device_token", sa.String(length=255), nullable=False),
        sa.Column("os_name", sa.String(length=50), nullable=True),
        sa.Column("os_version", sa.String(length=50), nullable=True),
        sa.Column("browser_name", sa.String(length=50), nullable=True),
        sa.Column("browser_version", sa.String(length=50), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("is_trusted", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_ip_address", sa.String(length=45), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_device_registrations_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_device_registrations")),
        sa.UniqueConstraint("device_token", name=op.f("uq_device_registrations_device_token")),
    )
    with op.batch_alter_table("device_registrations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_device_registrations_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_device_registrations_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "file_uploads",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=True),
        sa.Column("file_hash", sa.String(length=64), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("download_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_file_uploads_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_file_uploads")),
    )
    with op.batch_alter_table("file_uploads", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_file_uploads_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_file_uploads_user_id"), ["user_id"], unique=False)

    op.create_table(
        "form_submissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("form_type", sa.String(length=50), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("is_anonymous", sa.Boolean(), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitter_name", sa.String(length=255), nullable=True),
        sa.Column("submitter_email", sa.String(length=255), nullable=True),
        sa.Column("survey_id", sa.Integer(), nullable=True),
        sa.Column("completion_time_seconds", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_form_submissions_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_form_submissions")),
    )
    with op.batch_alter_table("form_submissions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_form_submissions_form_type"), ["form_type"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_form_submissions_id"), ["id"], unique=False)

    op.create_table(
        "tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("token_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("scopes", sa.JSON(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column("max_uses", sa.Integer(), nullable=True),
        sa.Column("allowed_ips", sa.JSON(), nullable=True),
        sa.Column("device_fingerprint", sa.String(length=255), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_by", sa.Integer(), nullable=True),
        sa.Column("revocation_reason", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["revoked_by"], ["users.id"], name=op.f("fk_tokens_revoked_by_users")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_tokens_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tokens")),
    )
    with op.batch_alter_table("tokens", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tokens_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_tokens_token_hash"), ["token_hash"], unique=True)
        batch_op.create_index(batch_op.f("ix_tokens_user_id"), ["user_id"], unique=False)

    op.create_table(
        "api_key_usage_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("api_key_id", sa.Integer(), nullable=False),
        sa.Column("endpoint", sa.String(length=255), nullable=False),
        sa.Column("method", sa.String(length=10), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("response_time_ms", sa.Integer(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("referer", sa.String(length=500), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["api_key_id"], ["api_keys.id"], name=op.f("fk_api_key_usage_logs_api_key_id_api_keys")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_key_usage_logs")),
    )
    with op.batch_alter_table("api_key_usage_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_api_key_usage_logs_id"), ["id"], unique=False)
        batch_op.create_index(
            "ix_api_key_usage_logs_key_created", ["api_key_id", "created_at"], unique=False
        )

    op.create_table(
        "course_experiments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("instructor_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("hypothesis", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("draft", "running", "paused", "completed", name="experiment_status"),
            nullable=False,
        ),
        sa.Column("variants", sa.JSON(), nullable=False),
        sa.Column("success_metrics", sa.JSON(), nullable=False),
        sa.Column("estimated_duration_days", sa.Integer(), nullable=False),
        sa.Column(
            "start_date", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["course_id"], ["courses.id"], name=op.f("fk_course_experiments_course_id_courses")
        ),
        sa.ForeignKeyConstraint(
            ["instructor_id"], ["users.id"], name=op.f("fk_course_experiments_instructor_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_course_experiments")),
    )
    with op.batch_alter_table("course_experiments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_course_experiments_course_id"), ["course_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_course_experiments_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_course_experiments_instructor_id"), ["instructor_id"], unique=False
        )

    op.create_table(
        "course_reviews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("is_verified_purchase", sa.Boolean(), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("is_featured", sa.Boolean(), nullable=False),
        sa.Column("helpful_count", sa.Integer(), nullable=False),
        sa.Column("reported_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["course_id"], ["courses.id"], name=op.f("fk_course_reviews_course_id_courses")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_course_reviews_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_course_reviews")),
        sa.UniqueConstraint("user_id", "course_id", name="uq_course_reviews_user_course"),
    )
    with op.batch_alter_table("course_reviews", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_course_reviews_course_id"), ["course_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_course_reviews_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_course_reviews_user_id"), ["user_id"], unique=False)

    op.create_table(
        "enrollments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "completed", "dropped", "suspended", name="enrollment_status"),
            nullable=False,
        ),
        sa.Column("progress_percentage", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("payment_amount", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("payment_currency", sa.String(length=3), nullable=True),
        sa.Column("payment_method", sa.String(length=50), nullable=True),
        sa.Column("transaction_id", sa.String(length=255), nullable=True),
        sa.Column("lessons_completed", sa.Integer(), nullable=False),
        sa.Column("total_lessons", sa.Integer(), nullable=False),
        sa.Column("total_time_spent_minutes", sa.Integer(), nullable=False),
        sa.Column("last_accessed_lesson_id", sa.Integer(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("certificate_issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("certificate_url", sa.String(length=500), nullable=True),
        sa.Column(
            "enrolled_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["course_id"], ["courses.id"], name=op.f("fk_enrollments_course_id_courses")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_enrollments_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_enrollments")),
        sa.UniqueConstraint("user_id", "course_id", name="uq_enrollments_user_course"),
    )
    with op.batch_alter_table("enrollments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_enrollments_course_id"), ["course_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_enrollments_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_enrollments_user_id"), ["user_id"], unique=False)

    op.create_table(
        "lessons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("lesson_type", sa.String(length=50), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("video_url", sa.String(length=500), nullable=True),
        sa.Column("audio_url", sa.String(length=500), nullable=True),
        sa.Column("transcript_url", sa.String(length=500), nullable=True),
        sa.Column("attachments", sa.JSON(), nullable=True),
        sa.Column("is_free_preview", sa.Boolean(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["course_id"], ["courses.id"], name=op.f("fk_lessons_course_id_courses")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lessons")),
        sa.UniqueConstraint("course_id", "slug", name="uq_lessons_course_slug"),
    )
    with op.batch_alter_table("lessons", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_lessons_course_id"), ["course_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_lessons_id"), ["id"], unique=False)

    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("jti", sa.String(length=255), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=True),
        sa.Column("session_id", sa.String(length=255), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_by", sa.Integer(), nullable=True),
        sa.Column("token_family", sa.String(length=255), nullable=True),
        sa.Column("parent_token_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["device_registrations.id"],
            name=op.f("fk_refresh_tokens_device_id_device_registrations"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_token_id"],
            ["refresh_tokens.id"],
            name=op.f("fk_refresh_tokens_parent_token_id_refresh_tokens"),
        ),
        sa.ForeignKeyConstraint(
            ["revoked_by"], ["users.id"], name=op.f("fk_refresh_tokens_revoked_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_refresh_tokens_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("jti", name=op.f("uq_refresh_tokens_jti")),
    )
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_refresh_tokens_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_refresh_tokens_token_family"), ["token_family"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_refresh_tokens_token_hash"), ["token_hash"], unique=True
        )
        batch_op.create_index(
            "ix_refresh_tokens_user_active", ["user_id", "is_revoked"], unique=False
        )

    op.create_table(
        "user_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(length=255), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("location", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["device_registrations.id"],
            name=op.f("fk_user_sessions_device_id_device_registrations"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_sessions_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_sessions")),
        sa.UniqueConstraint("session_id", name=op.f("uq_user_sessions_session_id")),
    )
    with op.batch_alter_table("user_sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_sessions_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_user_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "user_lesson_progress",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("lesson_id", sa.Integer(), nullable=False),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.Column("progress_percentage", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("time_spent_minutes", sa.Integer(), nullable=False),
        sa.Column("last_position_seconds", sa.Integer(), nullable=False),
        sa.Column("total_duration_seconds", sa.Integer(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_accessed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_accessed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["lesson_id"], ["lessons.id"], name=op.f("fk_user_lesson_progress_lesson_id_lessons")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_lesson_progress_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_lesson_progress")),
        sa.UniqueConstraint("user_id", "lesson_id", name="uq_user_lesson_progress_user_lesson"),
    )
    with op.batch_alter_table("user_lesson_progress", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_lesson_progress_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_user_lesson_progress_lesson_id"), ["lesson_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_user_lesson_progress_user_id"), ["user_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_lesson_progress", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_lesson_progress_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_lesson_progress_lesson_id"))
        batch_op.drop_index(batch_op.f("ix_user_lesson_progress_id"))

    op.drop_table("user_lesson_progress")
    with op.batch_alter_table("user_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_sessions_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_sessions_id"))

    op.drop_table("user_sessions")
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.drop_index("ix_refresh_tokens_user_active")
        batch_op.drop_index(batch_op.f("ix_refresh_tokens_token_hash"))
        batch_op.drop_index(batch_op.f("ix_refresh_tokens_token_family"))
        batch_op.drop_index(batch_op.f("ix_refresh_tokens_id"))

    op.drop_table("refresh_tokens")
    with op.batch_alter_table("lessons", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lessons_id"))
        batch_op.drop_index(batch_op.f("ix_lessons_course_id"))

    op.drop_table("lessons")
    with op.batch_alter_table("enrollments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_enrollments_user_id"))
        batch_op.drop_index(batch_op.f("ix_enrollments_id"))
        batch_op.drop_index(batch_op.f("ix_enrollments_course_id"))

    op.drop_table("enrollments")
    with op.batch_alter_table("course_reviews", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_course_reviews_user_id"))
        batch_op.drop_index(batch_op.f("ix_course_reviews_id"))
        batch_op.drop_index(batch_op.f("ix_course_reviews_course_id"))

    op.drop_table("course_reviews")
    with op.batch_alter_table("course_experiments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_course_experiments_instructor_id"))
        batch_op.drop_index(batch_op.f("ix_course_experiments_id"))
        batch_op.drop_index(batch_op.f("ix_course_experiments_course_id"))

    op.drop_table("course_experiments")
    with op.batch_alter_table("api_key_usage_logs", schema=None) as batch_op:
        batch_op.drop_index("ix_api_key_usage_logs_key_created")
        batch_op.drop_index(batch_op.f("ix_api_key_usage_logs_id"))

    op.drop_table("api_key_usage_logs")
    with op.batch_alter_table("tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tokens_user_id"))
        batch_op.drop_index(batch_op.f("ix_tokens_token_hash"))
        batch_op.drop_index(batch_op.f("ix_tokens_id"))

    op.drop_table("tokens")
    with op.batch_alter_table("form_submissions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_form_submissions_id"))
        batch_op.drop_index(batch_op.f("ix_form_submissions_form_type"))

    op.drop_table("form_submissions")
    with op.batch_alter_table("file_uploads", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_file_uploads_user_id"))
        batch_op.drop_index(batch_op.f("ix_file_uploads_id"))

    op.drop_table("file_uploads")
    with op.batch_alter_table("device_registrations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_device_registrations_user_id"))
        batch_op.drop_index(batch_op.f("ix_device_registrations_id"))

    op.drop_table("device_registrations")
    with op.batch_alter_table("courses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_courses_title"))
        batch_op.drop_index(batch_op.f("ix_courses_slug"))
        batch_op.drop_index("ix_courses_published_category")
        batch_op.drop_index(batch_op.f("ix_courses_instructor_id"))
        batch_op.drop_index(batch_op.f("ix_courses_id"))
        batch_op.drop_index(batch_op.f("ix_courses_category"))

    op.drop_table("courses")
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_keys_user_id"))
        batch_op.drop_index(batch_op.f("ix_api_keys_key_hash"))
        batch_op.drop_index(batch_op.f("ix_api_keys_id"))

    op.drop_table("api_keys")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_id"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("surveys", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_surveys_id"))

    op.drop_table("surveys")
    # ### end Alembic commands ###
